version: "3.7"

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: "xdebug-php-apache2:1.0"
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_mvc
      MYSQL_USER: php_mvc
      MYSQL_PASSWORD: php_mvc

volumes:
  mysql-data: